//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iTravelsEntities : DbContext
    {
        public iTravelsEntities()
            : base("name=iTravelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<it_st_Role> it_st_Role { get; set; }
        public virtual DbSet<it_User> it_User { get; set; }
        public virtual DbSet<it_User_Role> it_User_Role { get; set; }
    }
}
